### ISSUE TITLE
list all tools available in the docs

### ISSUE THREAD

**Issue by bboynton97** [stripe/agent-toolkit#1]
### Is your feature request related to a problem? Please describe.

Its unclear what tools are available. The only example is

```
"actions": {
    "payment_links": {
        "create": True,
    },
}
```

### Describe the solution you'd like

A list of tools in the docs or a link to the relevant API docs where this might be located.

### Describe alternatives you've considered

Searching other Stripe docs

**Comment by stevekaliski-stripe** [comment]
Great feedback! We'll update the README
