### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by MaximeGratens** [stripe/agent-toolkit#3]
### Describe the bug

Hello,

I'm trying to list payment links or to create a payment link using your prompt example. The problem is that the agent is answering an empty answer. I'm using gpt-4o

### To Reproduce

1. Ask Create a payment link for a new product called \"Test\" with a price of $100.
2. 
<img width="505" alt="image" src="https://github.com/user-attachments/assets/4e8ea1d4-1311-4ea4-b7ab-a48f584bc819">

### Expected behavior

A new payment link

### Code snippets

```Python
import { StripeAgentToolkit } from '@stripe/agent-toolkit/ai-sdk';
import { openai } from '@ai-sdk/openai';
import {
  convertToCoreMessages,
  experimental_wrapLanguageModel as wrapLanguageModel,
  streamText
} from 'ai';

// Instantiate a new Stripe Agent Toolkit.
const stripeAgentToolkit = new StripeAgentToolkit({
  secretKey: process.env.STRIPE_SECRET_KEY!,
  configuration: {actions: {
    paymentLinks: {
      create: true,
      read: true
    },
    products: {
      read: true,
      create: true,
    },
    prices: {
      read: true,
      create: true,
    },
  },},
});

export async function POST(req: Request) {
  const { messages } = await req.json();

  // Call the model and stream back the results.
  const result = await streamText({
    model: openai('gpt-4o'),
    tools: {
      ...stripeAgentToolkit.getTools(),
    },
    messages: convertToCoreMessages(messages),
  });

  return result.toDataStreamResponse();
}
```

### OS

macos

### Language version

typescript

### Library version

0.1.20

### API version

2024-10-28

### Additional context

Thank you for this library! I think we will build some coooool stuff with it!

**Comment by stevekaliski-stripe** [comment]
Thanks for submitting @MaximeGratens! If you look at the example in https://github.com/stripe/agent-toolkit/blob/main/typescript/examples/ai-sdk/index.ts, you'll see that we pass `maxSteps: 5` to the ai-sdk call:

```js
  const result = await generateText({
    model: model,
    tools: {
      ...stripeAgentToolkit.getTools(),
    },
    maxSteps: 5,
    prompt:
      'Create a payment link for a new product called "test" with a price of $100. Come up with a funny description about buy bots, maybe a haiku.',
  });
```

Try that and let me know if that works

**Comment by MaximeGratens** [comment]
Working thank you :)
